# Generated by Django 4.0.5 on 2022-08-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_user_name_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school_name',
            new_name='school',
        ),
    ]
