# Generated by Django 4.0.5 on 2022-08-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_verification_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
