# Generated by Django 4.0.5 on 2022-08-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_rename_is_verificate_user_is_verificated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='expiration_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
